### ISSUE TITLE
Not Mentioned - zoobee_launcher

### ISSUE THREAD

**Issue by justinmerrell** [kipr/KIPR-Development-Toolkit#1]
Trying to untangle the layers here, once the system has booted is zoobee_launcher called as the program to start all the KIPR services? And while we are at it, what is with the name? lol

The follow-up question is what method is being used to call the script on startup? 

And bonus question, I see that the Wombat is running LXDE is there any significance to it or just carried over from legacy hardware?

**Comment by Zacharyprime** [comment]
I know I've already answered this person to person.
But here is the answers for documentation:

### "Zoobee"
Zoobee Launcher is a name that I think Raj (might have been Mustafa) made up during development just to have something to put on stuff as they worked. I think of it as "zoo" because the controller naming convention is animals, and "bee" to match the last syllable of "wallaby".
###  Boot Operations 
#### Code Archaeology:
The image of the OS is setup in a pretty specific way. A lot of things are setup for the Wombat within files like /boot/config.txt

I'm not 100% of all the things that are setup within linux files such as boot instead of a software by KIPR.
I did some digging and found that the software is started on boot using a crontab.
You can see this by navigating to /var/spool/cron/crontabs and opening the file "pi".
There the crontabs are:
```
#@reboot /usr/bin/enableAP.sh
#@reboot /home/pi/task.sh
#@reboot /home/pi/zoobee_launcher.sh
```
As you can see, it is commented out, which means that this was how it was done early in development.

zoobee_launcher is a .sh that opens botui, and starts the node.js server (harrogate). When you click on the botguy icon in the desktop, this is what is being called.
task.sh seems to be an earlier version of enableAP.sh which explains the directory choices.
They both just do standard turning on wlan0, setting the ip to 192.168.125.1/24, etc.

#### How it works now:
It took me a little longer of digging to find where it actually called on boot.
Another way to call a script on boot is to put it in /etc/init.d/
/etc/init.d/botui starts a file /home/pi/.config/autostart/start.desktop

start.desktop just calls zoobee_launcher.sh (and kills botui on close),
which has the following:
```
echo [ZOOBEE] Launching harrogate server.js and botui GUI
sudo python wifi_configurator.py & 
cd harrogate
sudo node server.js &
sudo botui &
```
Note for Non-Linux Users: "&" runs the command on the left as a background task, the same as the SD writer script.

### OS
The OS used to be a version of raspbian.
If you run "cat /etc/os-release" on most Linux distros you can see who distributed the OS.
For those unfamiliar, Raspian is a modified version of debian for the Pi.
The desktop seems to have been customized so it is not the default look of raspian.

LXDE is arbitrary, it's just because Raj/Josh/Mustafa started with raspian.
You could probably swap it out with a new desktop environment and I doubt it would have any problems.
It does bring up the question of why Adafruit would have used LXDE instead of GNOME or something.

The background was added by me, for some reason the splash screen would have a loading time and I deemed it better to boot fast than show a KIPR logo. The desktop shows for a split second and kind of acts like a splash screen. 
Minecraft is also not standard, I added that because I view MC as educational.

I'm going to leave this issue open because:
Note to self: add to wiki or Wombat Dev Manual

**Comment by justinmerrell** [comment]
That is helpful to have, want to stick this info I'm the wiki or other documentation and close out this "issue"?

**Comment by Zacharyprime** [comment]
I have added this information to the Wiki for now.
